### ISSUE TITLE
Calculating skin joint matrix - use mesh node transform?

### ISSUE THREAD

**Issue by dakom** [KhronosGroup/glTF-Tutorials#17]
The tutorial states[1]

> The vertices have to be transformed with inverse of the global transform of the node that the mesh is attached to, because this transform is already done using the model-view-matrix, and thus has to be cancelled out from the skinning computation.

However, the spec states[2][3]:

> Client implementations should apply only the transform of the skeleton root node to the skinned mesh while ignoring the transform of the skinned mesh node.

Should the tutorial be changed to reflect the language of the spec?

[1] https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md
[2] https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#skins
[3] https://github.com/KhronosGroup/glTF/pull/1195

**Comment by dakom** [comment]
Along with the language of the tutorial, if the above is correct then I believe it would also mean changing this pseudocode:

```
jointMatrix(j) =
  globalTransformOfNodeThatTheMeshIsAttachedTo^-1 *
  globalTransformOfJointNode(j) *
  inverseBindMatrixForJoint(j);
```

to rather be:

```
jointMatrix(j) =
  globalTransformOfSkeletonRootNode^-1 *
  globalTransformOfJointNode(j) *
  inverseBindMatrixForJoint(j);
```

?

**Comment by shrinktofit** [comment]
I have the same question.

I don't know the meaning of `skin.skeleton` and how does it effect the calculation of the joint matrix.

In myself, I simply ignore it and do follow the tutorial (gltfTutorial_020_Skins)[https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md] and everything seems OK.

**Comment by emackey** [comment]
@donmccurdy Do you know the answer, or the right person to ask?

**Comment by donmccurdy** [comment]
Just replied on https://github.com/KhronosGroup/glTF/issues/1270. I believe it is correct to ignore it.

**Comment by emackey** [comment]
Having learned a bit more about skinning this year, I believe the tutorial's pseudocode is correct.

The vertex shader that's drawing a skinned mesh will attempt to draw it wherever in the world the node that owns the skinned mesh is located.  But the mesh isn't supposed to be there, instead the mesh is supposed to be wrapped around the bones, which might be completely elsewhere.  So the transform needs the inverse of the skinned mesh node's position, to recover the glTF "world" coordinates, and from there must travel to the joint's world coordinates.

The `skeleton` node is safe for implementations to ignore, and safe to omit from glTF.  I believe it serves as a marker between full-fledged heavyweight scene nodes, versus lighter-weight no-mesh-allowed joint nodes.  I believe it's purely a performance optimization, or a crutch for systems that demand to draw a sharp distinction between nodes and joints.

**Comment by javagl** [comment]
I think that, after a longer discussion and various fixes, this should also be resolved as of https://github.com/KhronosGroup/glTF-Tutorials/pull/64 

If it is not, feel free to reopen.
