### ISSUE TITLE
I have a simple question

### ISSUE THREAD

**Issue by awefire** [KhronosGroup/glTF-Tutorials#19]
I know that the buffers are base64 that converted from some string.
But what the string is?the points?the matrixs?
Can you give me a detailed information?
thanks in advance.

**Comment by lexaknyazev** [comment]
Data URI (base64) is just one of possible ways of representing binary data. Other two are an URI to an external file and GLB container format. Buffer itself is just an array of bytes. Its meaning is defined by buffer views and accessors.

**Comment by Febfire** [comment]
Thank you,lexaknyazev.
If i convert dae to gltf,which part of data in dae convert to buffers.That is my perplexity.

**Comment by emackey** [comment]
@Febfire Generally, mesh data, skins, and animation data ends up in the buffers, but everything else is in the JSON.

Take a look at the [glTF Overview](https://raw.githubusercontent.com/KhronosGroup/glTF/master/specification/2.0/figures/gltfOverview-2.0.0a.png).  The first several columns across the top explain the fundamental organization of data inside glTF.

**Comment by javagl** [comment]
Closing this, assuming that the basic idea has been conveyed.
