### ISSUE TITLE
Comma mistakes in "A Simple Texture" tutorial

### ISSUE THREAD

**Issue by lucagrementieri** [KhronosGroup/glTF-Tutorials#22]
The glTF file published in "A Simple Texture" tutorial does not work because a comma is missing before the "images" list.

Moreover there is a comma after the "asset" dictionary that causes a parse error.

**Comment by javagl** [comment]
Thanks, fixed via https://github.com/KhronosGroup/glTF-Tutorials/commit/27418391f13df2108419be4a6d43a38a77c8696e
