### ISSUE TITLE
如何更改gltf模型中心点位置

### ISSUE THREAD

**Issue by HuZhuangQiang** [KhronosGroup/glTF-Tutorials#26]
如何更改gltf模型中心点位置？
   实现效果：旋转模型时，围绕不同的中心点旋转

**Comment by javagl** [comment]
根据 google 翻译 / According to google translate: (https://translate.google.com/) 

> How to change the position of the gltf model center point?
> Achieve the effect: rotate around the different center points when rotating the model

This does not seem to be an issue with the tutorial, but rather a technical question that is specific for cesium.  Maybe this can be answered in the linked cesium issue report.

**Comment by Ybalrid** [comment]
Changing the center point of a mesh would be equivalent to changing the "origin" of all the vectors that describe each vertex. There's nothing in the glTF format that makes this "a thing you can do", but one easy solution is just to introduce a node to the scene that will parent the node that instanciate said mesh, and that contains the desired offset as the transform. Then when rotating that node, the object rotates around the point the author wanted to.

As far as I can tell, that's not an issue with the content of the tutorial here...
