### ISSUE TITLE
Structure of generic glTF tutorial 

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Tutorials#3]
This issue is intended for discussing proposals regarding the structure of the chapters of the generic glTF tutorial in https://github.com/KhronosGroup/glTF-Tutorials/pull/1 

The current structure of the chapters roughly corresponds to the "blocks" or "pages" of the https://github.com/javagl/gltfOverview/ .

But, for example, the section "Textures, Images, Samplers" does not really fit into gltfTutorial_005_MeshesTexturesImagesSamplers.md . Should there be a dedicated section for the (relatively complex and important) topic of `meshes` in glTF? Should the section about Textures simply be moved into gltfTutorial_006_MaterialsTechniquesProgramsShaders.md , or into a (short), dedicated section as well?

More generally: Should the chapters/sections be broken down, to be more fine-grained, or merged into larger ones? Should they have a more "hierarchical" structure? Should their order be changed?

**Comment by pjcozzi** [comment]
See my comments here: https://github.com/KhronosGroup/glTF-Tutorials/pull/1#discussion_r85649343

As for length, generally short sections are better as long as they are coherent.  Short sections (and short paragraphs) help the reader feel like they are making more progress.

**Comment by javagl** [comment]
Thanks for the detailed feedback. I'll go through this, add some responses and/or incorporate the "local" changes ASAP. For the overall structural changes, I'll wait a few days to see whether there is more feedback regarding this point.

**Comment by javagl** [comment]
I think this is now covered with the new structure that includes the incremental examples.
