### ISSUE TITLE
Code

### ISSUE THREAD

**Issue by seanbaxter** [KhronosGroup/glTF-Tutorials#38]
Is code available for these? I can't figure out the joint matrix calculation and would benefit from the code.

**Comment by emackey** [comment]
The joint matrices [are described here](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-joint-matrices) with this pseudocode:

```
jointMatrix(j) =
  globalTransformOfNodeThatTheMeshIsAttachedTo^-1 *
  globalTransformOfJointNode(j) *
  inverseBindMatrixForJoint(j);
```

The "inverseBindMatrix" comes from the glTF model skin definition.

A complete working example is included with the glTF Sample Viewer, here:

https://github.com/KhronosGroup/glTF-Sample-Viewer

In particular, `src/skin.js` might be what you're looking for.
