### ISSUE TITLE
Accompanying code for the glTF tutorials

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Tutorials#4]
The tutorial in https://github.com/KhronosGroup/glTF-Tutorials/pull/1 is supposed to give and introduction to glTF, and to show the interrelations of the elements of a glTF asset. 

When I started this, I thought that it could be nice to write this in the style of a "Tutorial for writing a minimalistic glTF renderer with JavaScript and WebGL". (This was somewhat ambitious, considering that I had never written any real JavaScript before). I tried to create such a renderer, _while_ writing the tutorial, but it turned out to be harder than I anticipated. Nevertheless, in the initial (internal, non-published) drafts, the chapters also contained more actual code snippets, that I took from this renderer. But as a last step before the pull request, I moved most of this into the (currently unpublished) "Summary" section. 

I assume that people who read such a tutorial **expect** some code that is at least _close_ to something that they can copy, paste and use directly. This raises the question of how "Real Code®" could be combined with this tutorial. 

Should the Real Code be shown in the "Summary" section? Or should there be dedicated tutorials for the _implementations_, considering that people migh want to implement renderers in JavaScript/Java/C++ using different libraries (three.js, assimp, ...) ?

I currently have a basic, "minimalistic" renderer in plain JavaScript+WebGL, which is not complete, but it properly renders the "Duck", at least. I think that something like this _could_ be helpful as accompanying code for the tutorial. But due to my lack of JavaScript skills and experience, **if** this was supposed to be published, it would have to undergo a _very_ critical review by a JavaScript expert. (My gut feeling is that there is waaay to much horrible, horrible JavaScript code out there, and I do _not_ want to throw more on this pile...)

**Comment by pjcozzi** [comment]
Perhaps add key code snippets to the current tutorials that help explain navigating a glTF assets, but keep the tutorial broad so it is useful to both runtime engine developers and tools/exporter developers.

Then have a separate tutorial on the renderer with more specific code examples for engines.

As for the JavaScript review, I may be able to do it or I'm sure someone on the Cesium team would volunteer.

If you want to see the JavaScript best practices we've learned over the years, see our [Coding Guide](https://github.com/AnalyticalGraphicsInc/cesium/tree/master/Documentation/Contributors/CodingGuide#coding-guide).

**Comment by javagl** [comment]
Basically the whole implementation-specific stuff has been removed from the initial draft (and only few of it was contained in the initial draft in the first place). Having separate tutorials for the glTF and its concepts in general (i.e. the current one) and other tutorials showing implementation details is certainly fine. So this issue here will basically be part of the "roadmap issue" that is about to be opened, and this one here can be closed.
