### ISSUE TITLE
how to calculate the global inverse transform

### ISSUE THREAD

**Issue by CppProgrammer23** [KhronosGroup/glTF-Tutorials#50]
Hi,

it looks like I didn't understand how to find the global inverse transform and the global transform.
for this formula: `jointMatrix(j) =
  globalTransformOfNodeThatTheMeshIsAttachedTo^-1 *
  globalTransformOfJointNode(j) *
  inverseBindMatrixForJoint(j);` the inverseBindMatrix is okay because we can get it from the skin attribute through the accessor and then bufferView etc.. but how to calculate the global inverse transform and the global transform?

**Comment by javagl** [comment]
The global transform is explained in [this section](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md#global-transforms-of-nodes). The pseudocode for the computation of the global transform could be

    Matrix computeGlobalTransformOf(Node node) {
        if (!hasParent(node)) return node.transform;
        else return computeGlobalTransformOf(node.parent) * node.transform;
    }

(Note: The "parent" is not stored directly in the JSON. This pseudocode should just illustrate the idea about how it is computed in theory).

The inverse of that transform is ... just the inverse of this matrix :-) Depending on the programming language/environment that you are using, you'll almost certainly have some sort of `Matrix` class that already offers some `invert` function. 

([Here](https://github.com/javagl/JglTF/blob/bb081a2e31b522bacb051d22053768d78c363814/jgltf-model/src/main/java/de/javagl/jgltf/model/MathUtils.java#L336) is one implementation of such a function (in Java, but so low-level that it only needs *arrays*, and thus, could trivially be ported to any other language), but usually, you do **not** have to write this sort of code on your own - every 3D vector/matrix library already offers that).

**Comment by CppProgrammer23** [comment]
cool, thank you.
if my node doesn't contain any scale vector, rotation vector or translation vector. the default value for rotation are all 0? the default value for scale are all 1? and the default value for translation are all 0?
my last question is: how to convert this vector `[ 0.259, 0.0, 0.0, 0.966 ]` to the matrix rotation given in this tutorial https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_004_ScenesNodes.md#global-transforms-of-nodes

**Comment by javagl** [comment]
Yes, 

- the default rotation is 0
- the default scale is 1
- the default translation is 0

meaning that the resulting matrix will be an *identity* matrix in this case.

> how to convert this vector `[ 0.259, 0.0, 0.0, 0.966 ]` to the matrix rotation

The value for the rotation is (in some sense not a "vector", but) a *quaternion* that describes the rotation. Again, most libraries for 3D vector math should already have some function to convert a quaternion into a 4x4 rotation matrix. (In doubt, another very low-level implementation is [shown here](https://github.com/javagl/JglTF/blob/bb081a2e31b522bacb051d22053768d78c363814/jgltf-model/src/main/java/de/javagl/jgltf/model/MathUtils.java#L301) , but one should preferably use an existing function for this if it is available...)

**Comment by CppProgrammer23** [comment]
thanks for these precious info
