### ISSUE TITLE
implementing an algorithm for the simpleSkin model from this github

### ISSUE THREAD

**Issue by CppProgrammer23** [KhronosGroup/glTF-Tutorials#51]
Hi,

I'm trying to implement an algorithm for the simpleSkin model: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleSkin/glTF

so I started with storing the inverseBindMatrices ( 2 matrices ) in a 2 mat4, then calculating the local transform according to the tutorial which says M = T * R * S, so this the initial state. since we don't have an hierarchy of nodes here, the global transform would be the local transform? correct?

since we have animation, I have to change the local transform matrix every time when the rotation changes (since we only have rotation animation, the scale and translation will stay the same)? and then calculate the new local transform and then the global transform as mention in the tutorial? once I have the global transform, I have to calculate the global inverse transform.
after all that I have to send the `u_jointMatrix` to the vertex shader.

is this correct?
thanks

**Comment by javagl** [comment]
There are comparatively many question about the skinning. There are some subtle details (e.g. about the skeleton) that can cause confusion here, and as a disclaimer, I have to mention that I'd also need to refresh my memories to talk about certain details of this topic.

> since we don't have an hierarchy of nodes here, the global transform would be the local transform? correct?

This is *technically* correct, **for this simple example**. Of course it should not be implemented with this assumption. (It could be worthwhile (and has been on my TODO list for a while now) to create a "SlightlyLessSimpleSkin" sample, that visually shows the effect of some subtle details)

Also, the remainder of what you said is correct. The actual computation of the `u_jointMatrix` (involving the weights and joint indices) has *some* room for errors, but with the description from https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-joint-matrices and the *simple* example (where it's easy to visually distinguish between "basically correct" and "totally wrong") should make this doable.

**Comment by CppProgrammer23** [comment]
Thank you, but my question is: why we need to do this `globalTransformOfNodeThatTheMeshIsAttachedTo^-1 *
  globalTransformOfJointNode(j)` if the first one is the inverse of the second one? we will get the identity matrix?

**Comment by javagl** [comment]
(I'll have to look at the example again to be 100% sure, but I'm sure enough to say that: ) This **may** be the identity matrix *in this particular sample*, but it may not be the identity matrix *in general*. To put it that way: It depends on 1. which are the joint nodes and 2. which node is the mesh attached to.

**Comment by CppProgrammer23** [comment]
or maybe, the global inverse transform is the inverse of the initial global transform before any animation. because I see that it's not variable according to the formula?

**Comment by javagl** [comment]
At the risk oof being annoying, once more, the disclaimer: That's one of the details where I'd have to spend a moment with the spec, code, model data, tutorial, the glTF Overview (and maybe even pen+pencil...).

But I'm reasonably sure that the inverse of the global transform has to be computed each time **during** the animation. So it has to be computed in *each* animation step. If this is the case, one could consider to 1. mention that in the tutorial and 2. make it clearer in the forumla, by not talking about the

    globalTransformOfNodeThatTheMeshIsAttachedTo^-1

to 

    globalTransformOfNodeThatTheMeshIsAttachedTo(t)^-1
    // At 't', the current animation time -------^     

---

Once more, the pointer to my current implementation (**not** claiming that this is 100% correct!), at https://github.com/javagl/JglTF/blob/bb081a2e31b522bacb051d22053768d78c363814/jgltf-viewer/src/main/java/de/javagl/jgltf/viewer/UniformGetterFactory.java#L424 

Translating the Java parlance to the language that I assume based on your GitHub name :-) :

- A "supplier" is just a thing that returns something (a float array, the matrix in this case) - basically something like a lambda `auto supplier = []() { return computeMatrix() };`
- The part that says

             Supplier<float[]> jointMatrixSupplier = MatrixOps
                .create4x4(nodeModel.createGlobalTransformSupplier())
                .invert4x4()
                ...
  creates such a supplier, where the `computeMatrix` (which is built with the `MatrixOps` class there) can be imagined as doing something like
    
      Matrix computeMatrix() {
          Matrix matrix = nodeThatTheSkinIsAttachedTo.getGlobalTransform();
          matrix.invert();
          ...
          return matrix;
      }

    **each time that the matrix is requested**. (I think this was the core of the question).

Of course, one could consider optimizations here. First of all, this approach is not only re-computing the matrix *in each animation step*, but *each time it is requested* (although that should be "each time the model is rendered", and thus, might happen less frequently than the animation steps). And in general, *not* re-computing the matrix each time would be straightforward, but *only* in pseudocode:

    Matrix Node::getGlobalMatrixInverted() {
        if (anyAncestorWasAnimated) { // Have to re-compute it...
            this.cachedInvertedGlobal = computeGlobal().invert();
        }
        return this.cachedInvertedGlobal;
    }

The crux here would be to maintain the `anyAncestorWasAnimated` state accordingly...

**Comment by CppProgrammer23** [comment]
I'm getting more confused now. if I have to use this: `globalTransformOfNodeThatTheMeshIsAttachedTo(t)^-1` that's mean that I have to calculate the `globalTransform` accordingly since it's its inverse.

In our case (`simpleSkin` model) we have 2 joints so we have 2 `globalTransform` at a time thus 2 `globalTransformOfNodeThatTheMeshIsAttachedTo^-1`.

so for instance, in my code I have to use something like this:
`for (unsigned l = 0; l < myMeshes.at(0).numOfJoints; l++)
{
	jointM[l] = globalInverseTransform.at(l) * globalTransform.at(l) * myMeshes.at(0).inverseBindMatrice.at(l);
}`

`inverseBindMatrice` is a vector of mat4 which is of size 2 here (I mean 2 mat4)
`jointM` is an array of mat4 (size 2)
so as you can see, `globalInverseTransform` and `globalTransform` are calculated each time during the animation.

and to send the u_jointMatrix to the vertex shader I have to do something like that:
`for (unsigned l = 0; l < myMeshes.at(0).numOfJoints; l++) 
{
	std::string name = "u_jointMatrix[" + std::to_string(l) + "]";
	int jointMatrixLoc = glGetUniformLocation(program, name.c_str());
	glUniformMatrix4fv(jointMatrixLoc, 1, GL_FALSE, glm::value_ptr(jointM[l]));
}`

what do you think of my code?

**Comment by javagl** [comment]
> what do you think of my code?

In a review, I'd say that `1` is a bad variable name. (Yeah, it's `l`, but that's the point...)

But seriously: I *think* that I noticed something that might be the root cause of some confusion here (and one reason for an [earlier comment](https://github.com/KhronosGroup/glTF-Tutorials/issues/51#issuecomment-826298564) ) : 

> In our case (`simpleSkin` model) we have 2 joints so we have 2 `globalTransform` at a time thus 2 `globalTransformOfNodeThatTheMeshIsAttachedTo^-1`.

Notice that this is the `globalTransformOfNodeThatTheMeshIsAttachedTo`, and **not** the `globalTransformOfTheJointNode`. Specifically, the mesh is only (and always) attached to *one* node. And even more specifically: The [SimpleSkin example](https://github.com/KhronosGroup/glTF-Sample-Models/blob/master/2.0/SimpleSkin/glTF/SimpleSkin.gltf#L7) has the following nodes:
``` 
  "nodes" : [ {
    "skin" : 0,
    "mesh" : 0
  }, {
    "children" : [ 2 ],
    "translation" : [ 0.0, 1.0, 0.0 ]
  }, {
    "rotation" : [ 0.0, 0.0, 0.0, 1.0 ]
  } ],
```

These are three nodes: The first one is the one that the mesh is attached to. The second and third one are the actual joint nodes (as indicated by the `"joints" : [ 1, 2 ]` in the actual `"skin"` of that file).

---

**Very** roughly speaking, you might imagine this as follows: The joint nodes are the "skeleton" that determines the *deformation* of that mesh. But the skinned mesh itself can appear *anywhere* in the scene (because the node *that the mesh is attached to* can have any transform) 

This means that for the computation of the joint matrix, the global transform (of the node that the mesh is attached to) has to be "computed **out**" - meaning "to be multipled with the *inverse*". 

So referring to your code
```
for (unsigned l = 0; l < myMeshes.at(0).numOfJoints; l++) { 
    jointM[l] = globalInverseTransform.at(l) * globalTransform.at(l) * myMeshes.at(0).inverseBindMatrice.at(l); 
}
```
the part `globalInverseTransform.at(l)` is probably wrong. It should be something like
```
void computeAllThatFor(Node nodeThatTheMeshIsAttachedTo) {

    // This is computed for the node that the skinned mesh
    // is attached to, and NOT for each joint node!
    Matrix globalInverse = nodeThatTheMeshIsAttachedTo.getGlobalTransform().invert();
             
    for (unsigned l = 0; l < myMeshes.at(0).numOfJoints; l++) { 
        jointM[l] = globalInverse * globalTransform.at(l) * myMeshes.at(0).inverseBindMatrice.at(l); 
    }
    ...
}
```

**Comment by CppProgrammer23** [comment]
So here the globalInverse would be the inverse of M = T * R * S with T is 0, R is 0 and S is 1? I’ve give it a try but not working

**Comment by CppProgrammer23** [comment]
Meaning that the `globalTransform` still the same which is calculated from the beginning before any animation is applied, same for the `inverseBindMatrices` and the `globalInverseTransform` will change every time during the animation and holds the value of (in our case) rotation (translation will be 0 ans scale 1).

I think it’s correct this way?

**Comment by CppProgrammer23** [comment]
Hi,

I have developed the algorithm and the rotation works but the base of the model is moving. that's mean, the weights are not working. what could be the problem?
