### ISSUE TITLE
Update and simplify the skinning section

### ISSUE THREAD

**Issue by javagl** [KhronosGroup/glTF-Tutorials#54]
The computation of the joint matrices at https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-joint-matrices is basically based on an older state of the specifiction, where some aspects of the skinning had not yet been clear (in general, and for me in particular).

Based on a discussion in https://github.com/KhronosGroup/glTF-Sample-Models/issues/312 and what I have read in the issues that are linked from that, the `globalTransformOfNodeThatTheMeshIsAttachedTo^-1` can be omitted. (Note that the current description is not *wrong*, it is just more complicated than it needs to be).

Some further verification will happen before that, and the https://github.com/javagl/gltfOverview will also have to be updated accordingly.

**Comment by CppProgrammer23** [comment]
Yes, I think some verifications are needed because when I omitted the `globalTransformOfNodeThatTheMeshIsAttachedTo^-1`, I got something wrong.

**Comment by javagl** [comment]
The question may sound more sarcastic than it is intended to be, but: Was it **right** when you *included* this transform? 

From my first, basic tests, the results when including it and excluding it had (visually) be the same. Descriptions like https://github.com/KhronosGroup/glTF/issues/1270#issuecomment-401417449 are quite elaborate, and doing the math (again, from scratch) is something that I'll hardly be able to allocate enough time for. So I have to rely on (my tessts, but not these tests alone, but also) people confidently saying: "Yes, this is mathematically correct".

**Comment by CppProgrammer23** [comment]
Yes it was right when I included this transform.

Without including it, it's "Mathematically correct" but "engineering wrong".

Seems like some works need to be done.

**Comment by scurest** [comment]
The math isn't hard, that's why I can be confident. Just run through it.

The tutorial says (I will abbreviate `globalTransformOfNodeThatTheMeshIsAttachedTo` as `globalTransformOfMeshNode`)

    mat4 u_jointMat[j] =
        globalTransformOfMeshNode^-1 *
        globalTransformOfJointNode(j) *
        inverseBindMatrixForJoint(j);

    mat4 skinMat =
        a_weight.x * u_jointMat[int(a_joint.x)] +
        a_weight.y * u_jointMat[int(a_joint.y)] +
        a_weight.z * u_jointMat[int(a_joint.z)] +
        a_weight.w * u_jointMat[int(a_joint.w)];
    vec4 pos = u_modelViewMatrix * skinMat * vec4(a_position,1.0);

`globalTransformOfMeshNode^-1` is a constant on the left of the every term in `skinMat`, so we can factor it out, rewriting as

    mat4 u_jointMat[j] =
        globalTransformOfJointNode(j) *
        inverseBindMatrixForJoint(j);

    mat4 skinMat =
        a_weight.x * u_jointMat[int(a_joint.x)] +
        a_weight.y * u_jointMat[int(a_joint.y)] +
        a_weight.z * u_jointMat[int(a_joint.z)] +
        a_weight.w * u_jointMat[int(a_joint.w)];
    vec4 pos = u_modelViewMatrix * globalTransformOfMeshNode^-1 * skinMat * vec4(a_position,1.0);

Now we need to expand `u_modelViewMatrix`. The tutorial does not say how this is defined, but I am assuming what would be correct for an unskinned mesh.

    mat4 u_modelViewMatrix =
        u_viewMatrix *                   // view matrix
        globalTransformOfMeshNode;       // model matrix

which means that

    u_modelViewMatrix * globalTransformOfMeshNode^-1 =
    u_viewMatrix * globalTransformOfMeshNode * globalTransformOfMeshNode^-1 =
    u_viewMatrix

This is consistent with the tutorial's description of the function of `globalTransformOfMeshNode^-1`

> The vertices have to be transformed with inverse of the global transform of the node that the mesh is attached to, because **this transform is already done using the model-view-matrix**, and thus **has to be cancelled out** from the skinning computation.

Inserting this gives the final simplified form

    mat4 u_jointMat[j] =
        globalTransformOfJointNode(j) *
        inverseBindMatrixForJoint(j);

    mat4 skinMat =
        a_weight.x * u_jointMat[int(a_joint.x)] +
        a_weight.y * u_jointMat[int(a_joint.y)] +
        a_weight.z * u_jointMat[int(a_joint.z)] +
        a_weight.w * u_jointMat[int(a_joint.w)];
    vec4 pos = u_viewMatrix * skinMat * vec4(a_position,1.0);

**Comment by javagl** [comment]
@scurest Thanks for the writeup. I'm increasingly convinced :-) My guess/gut feeling now is that this matrix may have been required in the original (glTF 1.0) skinning, because there, we also had this "bind shape matrix" (which has been omitted in glTF 2.0). (At least, that would explain why some (now apparently useless) matrix found its way into all the formulas and documents...).

I'll try to schedule an update for the tutorial and overview soon.

**Comment by cx20** [comment]
I don't understand this issue very well, but I think it has something to do with the following issue.
https://github.com/KhronosGroup/glTF-Sample-Models/issues/83

**Comment by javagl** [comment]
In terms of omitting the unnecessary global transform, this should also be fixed by https://github.com/KhronosGroup/glTF-Tutorials/pull/64
