### ISSUE TITLE
Publish this repo as a website

### ISSUE THREAD

**Issue by pjcozzi** [KhronosGroup/glTF-Tutorials#6]
GitHub has some new options: https://github.com/blog/2289-publishing-with-github-pages-now-as-easy-as-1-2-3

Looks like there are some custom theme options as well.

CC @Khronoswebmaster

**Comment by javagl** [comment]
I just tried it out locally on the fork, but had to do a (hard) rollback. It seems like there are some hiccups with the relative links. Although they should work according to [a recent post](https://github.com/blog/2290-relative-links-for-github-pages), they still seemed to remain .MD links for me. Maybe this will be fixed (the functionality is still rather new), or the webmaster manages to let the links be translated properly.

**Comment by pjcozzi** [comment]
Thanks for looking into it.  Do you want to submit a bug to GitHub?

**Comment by javagl** [comment]
I just stumbled over this issue, while looking for issues that could potentially be closed, and tried it again (in my fork) : It seems like relative links are now working, and publishing this as a website is really just about [checking the 'Yeah, publish it!' check box](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site).

The result can be seen at https://javagl.github.io/glTF-Tutorials/gltfTutorial/

(It seems like I cannot do this for the Khronos repo, but the webmaster could give it a try...)

**Comment by pjcozzi** [comment]
Sounds great, can we upload any links to this repo to link to the website instead where appropriate?

**Comment by Khronoswebmaster** [comment]
Would you want this published to some place like khronos.org/gltf/tutorials ?

**Comment by pjcozzi** [comment]
Could be great! 😄

**Comment by gerroon** [comment]
Does anyone know how to get a pdf version of this site or the markdown versions?

**Comment by Khronoswebmaster** [comment]
Created PR https://github.com/KhronosGroup/glTF-Tutorials/pull/37 allowing us to mirror this repository at khronos.org/gltf/tutorials and at https://github.khronos.org/glTF-Tutorials/

**Comment by javagl** [comment]
Since https://github.khronos.org/glTF-Tutorials/gltfTutorial/ has been online for quite a while now, I think this can be closed.
