### ISSUE TITLE
Question about keyframe compression

### ISSUE THREAD

**Issue by StoneWolf** [KhronosGroup/glTF-Tutorials#60]
Is it possible to customize keyframe compression? I'm mostly interested by translations, which seem to be using half-precision floats when compressed. If I'm not mistaken, this would produce jittery animations when uncompressed translations base values are, for example, 1000.0 and change by orders of magnitude less, for example 0.001.

This is especially visible (given that my ozz-animation implementation is correct) in this scene: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC

Most of the animated objects appear jittery, especially the helicopter.

**Comment by donmccurdy** [comment]
Are you asking about a particular type of compression? This is the glTF tutorial repository and probably not the right place, but the base glTF spec doesn't provide keyframe compression itself. glTF extensions can, and one possible compression option is defined by [EXT_meshopt_compression](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Vendor/EXT_meshopt_compression) and implemented in various tools.
