### ISSUE TITLE
Clarify component order for quaternions in scene/node page

### ISSUE THREAD

**Issue by alinen** [KhronosGroup/glTF-Tutorials#61]
APIs/Tools vary in whether they put the w component of a quaternion is first or last. Under the rotation section, explicitly say that the order used by GLTF is x,y,z,w.

**Comment by alinen** [comment]
Unless it's difficult to change the tutorial, you should add it there to make it easier for people to learn and adopt glTF. For example, you don't make readers look up whether matrices use column-major order or row-major order. This is helpful!

For example, perhaps say this: 

The rotation is given as a quaternion. The mathematical background of quaternions is beyond the scope of this tutorial. For now, the most important information is that a quaternion is a 4-tuple (x,y,z,w) that represents a rotation about an arbitrary angle and around an arbitrary axis. For example, the quaternion [ 0.259, 0.0, 0.0, 0.966 ] describes a rotation about 30 degrees, around the x-axis. So this quaternion can be converted into a rotation matrix, as shown in Image 4d.

**Comment by emackey** [comment]
The tutorial is all here on GitHub.  Would you be willing to reformulate these suggestions in the form of a pull request?  I think @javagl would probably accept a PR with these types of clarifications (and @javagl we should update the contributors/acknowledgement list if this happens).

**Comment by alinen** [comment]
Yes, of course

**Comment by javagl** [comment]
I can also schedule an update for this. I'm a bit busy with other stuff right now, but there are some pending issues/update requests for the tutorial, maybe I can sweep some of them out e.g. during the weekend.
