### ISSUE TITLE
Cannot replicate Skin glTF-Tutorial data contents

### ISSUE THREAD

**Issue by nyers33** [KhronosGroup/glTF-Tutorials#62]
To get a grasp of the gltf format, I'm writing a simple loader that can load animation (vertex skinning) data. I follow the [Skin glTF-Tutorial](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md) and use the same basic glTF asset and fail to extract some of the data contents from it.

The positions of the vertices and the indices of the triangles are OK.

inverseBindMatrices:
```
1.0   0.0   0.0   -0.5   
0.0   1.0   0.0   -1.0   
0.0   0.0   1.0    0.0   
0.0   0.0   0.0    1.0  
```
Instead of the pure -1.0 translation in the y direction. My extraction data matches min/max data from the "accessors":
```
{
    "bufferView" : 3,
    "byteOffset" : 0,
    "componentType" : 5126,
    "count" : 2,
    "type" : "MAT4",
    "max" : [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -0.5, -1.0, 0.0, 1.0 ],
    "min" : [ 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, -0.5, -1.0, 0.0, 1.0 ]
}
```
How can I get an additional -0.5 translation in x? This doesn't align with the derivation with the inverse bind matrices.

"JOINTS_0":
```
0, 1, 0, 0
0, 0, 0, 0
0, 1, 0, 0
0, 0, 0, 0
0, 1, 0, 0
0, 0, 0, 0
0, 1, 0, 0
0, 0, 0, 0
0, 1, 0, 0
0, 0, 0, 0
```

"WEIGHTS_0" is the same.

The gltf asset loads and displays well in the [online viewer](https://gltf-viewer.donmccurdy.com/).
[skin.zip](https://github.com/KhronosGroup/glTF-Tutorials/files/7489253/skin.zip)

Thank you!

**Comment by javagl** [comment]
There has been some back and forth regarding the section and the associated model (e.g. https://github.com/KhronosGroup/glTF-Tutorials/issues/44 ). Admittedly, and unfortunately, I have not yet allocated enough time to _really_ take a closer look at all this again (except for fixes like https://github.com/KhronosGroup/glTF-Tutorials/pull/41 ).

But in this case, from a quick (!) look, I think that you are correct: The seciton at https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-skin describes the `inverseBindMatrices` **without** the translation of -0.5 in x-direction that it actually contains.

I'll try to have a closer look and verify that as soon as possible, and schedule an update of this section. There is a related issue, https://github.com/KhronosGroup/glTF-Tutorials/issues/54 , and I'd like to do this in one pass, but if this one is *only* about the matrix in the text, it could be quick(er), dedicated update.

**Comment by nyers33** [comment]
Thank you, and sorry for not using the search function!
