### ISSUE TITLE
gltfTutorial_020_Skins.md typo

### ISSUE THREAD

**Issue by boguscoder** [KhronosGroup/glTF-Tutorials#69]
gltfTutorial_020_Skins in section [The skinning joints and weights](https://github.com/KhronosGroup/glTF-Tutorials/blob/master/gltfTutorial/gltfTutorial_020_Skins.md#the-skinning-joints-and-weights) says

> except the first two vertices are influenced only by joint 0, and the **last two vertices are influenced only by joint 1**

But the bold part doesn't correspond to data shown:

’’’
Vertex 8:  0, 1, 0, 0,
Vertex 9:  0, 1, 0, 0,
’’’

**Comment by boguscoder** [comment]
Sill me, false alarm

**Comment by javagl** [comment]
If you want to read a looong discussion, uncluding my struggle to describe this as it is now, see https://github.com/KhronosGroup/glTF-Tutorials/pull/64#issuecomment-968287758 ;-) 

If you have any idea about how to make this clearer or easier to understand, or avoid the confusion that led to this issue: Feedback is always appreciated.

**Comment by boguscoder** [comment]
I think what's not perfectly obvious is that "last two" vertices are only affected by one joint because of 0 weights, but this fact is mentioned only in next section, so linear reading leads to confusion
