### ISSUE TITLE
Hi, what is the right thing to do if JOINT_0 comes in a model in the format short 5123?

### ISSUE THREAD

**Issue by 3dportable** [KhronosGroup/glTF-Tutorials#79]
![image](https://user-images.githubusercontent.com/60338408/219624639-109a9852-7383-45fb-809f-9b2f3657cfa7.png)

Hi, some models come with JOINT_0 in short 5123 format.
Please tell me how to process it correctly?

And another question, how to properly show a model without a skeleton and skin? Should I use a different shader or create a skin  programmatically?

**Comment by javagl** [comment]
I think that the right thing to do is ... _nothing_ 🙂 

The `glVertexAttribPointer` should automatically _accept_ the `jointsComponentType==GL_UNSIGNED_SHORT` , and convert the `unsigned short` values to `float` internally. At least, that's what my interpretation was when I tried to refresh my memory by re-reading the documentation of that function, in the context of a related issue - see https://github.com/KhronosGroup/glTF/issues/2249#issuecomment-1408891386

**Comment by 3dportable** [comment]
thanks
