### ISSUE TITLE
can Mesh be used in several different Skins? should I provide for this when loading glb?

### ISSUE THREAD

**Issue by 3dportable** [KhronosGroup/glTF-Tutorials#80]
can Mesh be used in several different Skins? should I provide for this when loading glb?

**Comment by javagl** [comment]
A mesh can be used with different skins. 

Note that a `mesh` itself is not really "rendered" on the screen. Consider a glTF with the following **nodes(!)**:
```
        {
            "name": "nodeA",
            "mesh": 0,
            "translation": [ 0.0, 0.0, 0.0 ]
        },
        {
            "name": "nodeB",
            "mesh": 0,
            "translation": [ 10.0, 10.0, 10.0 ]
        }
```
Note that **both** nodes refer to mesh **`0`**. This means that when this glTF is rendered, then the mesh **`0`** will be rendered **twice** (here: at different positions).

Consequently, you could have
```
        {
            "name": "nodeA",
            "mesh": 0,
            "skin": 0,
            "translation": [ 0.0, 0.0, 0.0 ]
        },
        {
            "name": "nodeB",
            "mesh": 0,
            "skin": 1,
            "translation": [ 10.0, 10.0, 10.0 ]
        }
```
where the same mesh is used in both nodes, but associated with different _skins_.

**Comment by 3dportable** [comment]
ok, thanks
you are right, class Node is most suitable for this purpose
