### ISSUE TITLE
Some phones don't draw models if indicesComponentType=5125-GL_UNSIGNED_INT. But they draw fine if indicesComponentType=5123-GL_UNSIGNED_SHORT. I think it may be related to the support on the phone OpenGLES3+. Or are there other reasons?

### ISSUE THREAD

**Issue by 3dportable** [KhronosGroup/glTF-Tutorials#82]
![image](https://user-images.githubusercontent.com/60338408/220519029-e019347a-b753-4fef-8bde-909751a56af6.png)

Some phones don't draw models if indicesComponentType=5125-GL_UNSIGNED_INT. But they draw fine if indicesComponentType=5123-GL_UNSIGNED_SHORT. I think it may be related to the support on the phone OpenGLES3+. 
Or are there other reasons?

**Comment by javagl** [comment]
That's almost certainly the (only) reason.

GLES 2.0: https://registry.khronos.org/OpenGL-Refpages/es2.0/xhtml/glDrawElements.xml 

> type: Specifies the type of the values in indices. Must be GL_UNSIGNED_BYTE or GL_UNSIGNED_SHORT.

GLES 3.0: https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glDrawElements.xhtml

> type: Specifies the type of the values in indices. Must be one of GL_UNSIGNED_BYTE, GL_UNSIGNED_SHORT, or GL_UNSIGNED_INT.

(There are extensions for supporting `GL_UNSIGNED_INT` in 2.0, but I don't know how widely these are supported)

**Comment by lexaknyazev** [comment]
- For OpenGL ES 2.0, check for the [`GL_OES_element_index_uint`](https://registry.khronos.org/OpenGL/extensions/OES/OES_element_index_uint.txt) extension string presence.
- For WebGL 1.0, enable the [`OES_element_index_uint`](https://registry.khronos.org/webgl/extensions/OES_element_index_uint/) extension.

**Comment by 3dportable** [comment]
thank
