### ISSUE TITLE
Animation in model without skeleton and bones

### ISSUE THREAD

**Issue by 3dportable** [KhronosGroup/glTF-Tutorials#83]
![image](https://user-images.githubusercontent.com/60338408/221201630-91a8d32b-82c5-4c1d-9f6f-a37b8b9b0ea3.png)

hi, I'm studying an interesting model and I don't understand how animation works in it, there is no skeleton and bones in it, but it moves. Do you have detailed documentation about this animation method?

**Comment by javagl** [comment]
Animation does not require a "skeleton" or "bones". (These terms are mainly used in the context of _vertex skinning_).

Look at the [`AnimatedTriangle`](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/AnimatedTriangle) sample model, which is supposed to be the most simple possible animated glTF model. The [`animation.channel`](https://github.com/KhronosGroup/glTF-Sample-Models/blob/2e8cffb70534c183e8a32f3afa5f4fac36a7a416/2.0/AnimatedTriangle/glTF-Embedded/AnimatedTriangle.gltf#L39) in this model simply modifies the `rotation` of node `0`. Similarly, in the drone model, there are _many_ nodes and _many_ animations, but all these animations just affect the `rotation/translation/scale` of different nodes.

**Comment by 3dportable** [comment]
ok, thank you.
