### ISSUE TITLE
does gltf support metadata， KV string map for example

### ISSUE THREAD

**Issue by cmingxu** [KhronosGroup/glTF-Tutorials#84]
I want store some metadata on a gltf,  anyway i can store these data in it ?

**Comment by javagl** [comment]
There is the [`KHR_xmp_json_ld`](https://github.com/KhronosGroup/glTF/tree/main/extensions/2.0/Khronos/KHR_xmp_json_ld) extension that allows storing metadata. 

(On a more fine-grained level, there is a PR for [structural metadata](https://github.com/KhronosGroup/glTF/pull/2151), but this is not reviewed/merged yet. Also, for _some_ cases, when the data is **only** supposed to be used _internally_, then you can theoretically store arbitrary data in the `extras` property of nearly every object in glTF)

**Comment by javagl** [comment]
I'll just close this as a cleanup, assuming that it is answered sufficiently.
