### ISSUE TITLE
is it possible to somehow determine in which units of measurement the model is located? Millimeters, centimeters, meters or inches?

### ISSUE THREAD

**Issue by 3dportable** [KhronosGroup/glTF-Tutorials#86]
is it possible to somehow determine in which units of measurement the model is located? Millimeters, centimeters, meters or inches?

**Comment by javagl** [comment]
The easiest way to determine this is via https://registry.khronos.org/glTF/specs/2.0/glTF-2.0.html#coordinate-system-and-units : 

> **The units for all linear distances are meters.**

Yes, _creators_ of models can do whatever they want. (Even in the official sample models, there are some models that do not have a "reasonable" size in terms of their bounding box - see [this issue](https://github.com/KhronosGroup/glTF-Sample-Models/issues/327#issuecomment-898958543) for some examples). But one purpose of putting this information into the specification is that users generally should be able to _rely_ on that, and do _not_ have to deal with something like `"asset": { "units": "nauticMiles" } }` or so...
