### ISSUE TITLE
how to use schema.json in gltf2.0

### ISSUE THREAD

**Issue by chen21439** [KhronosGroup/glTF-Tutorials#87]
[[featureIdTexture.schema.json](https://github.com/CesiumGS/glTF/blob/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features/schema/featureIdTexture.schema.json).](https://github.com/CesiumGS/glTF/tree/3d-tiles-next/extensions/2.0/Vendor/EXT_mesh_features)

for example in the document,it use shema.json to generate featureId for each vertex,i want to know waht software can do this ,can you give me more information @javagl

**Comment by javagl** [comment]
As far as I know, there is no software that can assign feature IDs to vertices directly. (I have heard rumors that Blender can assign ~"per-vertex attributes", but this would not be exported to glTF by default). You have to _know_ which vertex should receive which ID, and assign this information to the vertices when you are creating the glTF. 

I'm also not aware of any open-source software or library that can (officially) _generate_ glTFs that have this extension. I recently added support for this extension in [`3d-tiles-tools`](https://github.com/CesiumGS/3d-tiles-tools/tree/main), and an example for assigning feature IDs to vertices is shown in the [`ExtMeshFeaturesDemo.ts`](https://github.com/CesiumGS/3d-tiles-tools/blob/6d89d61ee2dda42cee6986ab1fa85ceeec15c1c7/demos/ExtMeshFeaturesDemo.ts#L1). But **this is not part of any official API, and it may be changed arbitrarily or even removed at any time**. Maybe there will be broader support for this extension in the future.

**Comment by chen21439** [comment]
thank you for you reply,i pull the 3d-tiles-tools and run the ExtMeshFeaturesDemo.ts but it throw a error 
![image](https://github.com/KhronosGroup/glTF-Tutorials/assets/141226184/74ff5b77-6c1c-49b5-942b-46e7bdead517)
in method savePixelsInternal 

> const data = putPixelData(pixels, new Uint8Array(width * height * channels));

the data is empty

**Comment by javagl** [comment]
From a quick glance, this error seems to come from the `ndarray` library. What happens when you run this test:
```typescript
import { savePixels } from "ndarray-pixels";
import NdArray from "ndarray";

async function runTest() {
  const sizeX = 3;
  const sizeY = 3;
  const pixels = NdArray(new Uint8Array(sizeX * sizeY), [sizeX, sizeY]);
  for (let x = 0; x < pixels.shape[0]; x++) {
    for (let y = 0; y < pixels.shape[1]; y++) {
      pixels.set(x, y, x * sizeY + y);
    }
  }
  console.log("pixels ", pixels);
  const image = await savePixels(pixels, "image/png");
  console.log("image ", image);
}

runTest();
```

**Comment by chen21439** [comment]
@javagl ![image](https://github.com/KhronosGroup/glTF-Tutorials/assets/141226184/44318c46-84e2-402a-8ccf-f89606550bda) it shows that

**Comment by chen21439** [comment]
i think the problem occur in  ndarray-pixels-node.cjs putPixelData()  
![image](https://github.com/KhronosGroup/glTF-Tutorials/assets/141226184/aef20892-8bbe-476f-8a4b-22f1c5724163)

**Comment by javagl** [comment]
There seems to be a difference between a JavaScript and a TypeScript context. I haven't understood all the details here yet, but opened https://github.com/donmccurdy/ndarray-pixels/issues/156 

As a quick fix, you could change the code that fills the pixels, to anticipate that there are `4` channels (and the values are written into channel `3`):
```
  // Create an image with integer values that serve as feature IDs
  const sizeX = 3;
  const sizeY = 3;
  const pixels = NdArray(new Uint8Array(sizeX * sizeY * 4), [sizeX, sizeY, 4]);
  for (let x = 0; x < pixels.shape[0]; x++) {
    for (let y = 0; y < pixels.shape[1]; y++) {
      pixels.set(x, y, 3, x * sizeY + y);
    }
  }
```
(I haven't tested it thoroughly, but it should solve the issue for now).

But note that the example only generates "some dummy data", **only** for testing the implementation of the extension. I have also opened https://github.com/CesiumGS/3d-tiles-tools/issues/62 to track the process to create an extended/updated/fixed demo.

**Comment by javagl** [comment]
I assume that this can be closed for now.

But a small aside: Somone wrote a nice summary of how to add metadata information to models in Blender at https://community.cesium.com/t/gltf2-0-in-ue5-2-metadata-ext-structural-metadata-ext-mesh-features/26873/8 . There may be some manual steps involved, but it will certainly provide a good starting point.
